'use strict';

/**
 * @file quiz.session.model.js
 * @description Quiz participation — anonymous session or linked to a lead.
 *
 * Before pre-registration : sessionToken identifies the participant anonymously.
 * After pre-registration  : lead (ObjectId) is set, sessionToken is kept.
 * period 'YYYY-MM'        : used to filter the monthly leaderboard.
 *
 * Server-issued lifecycle (anti-cheat): a `pending` session is created when the
 * questions are served, storing the exact `servedQuestionIds`. Submission scores
 * against that stored set — the client can never shrink the denominator — and
 * flips the session to `completed`. Abandoned `pending` sessions carry an
 * `expiresAt` and are reaped by a TTL index; completed sessions set it to null
 * so the leaderboard keeps them.
 */

const mongoose = require('mongoose');

const quizSessionSchema = new mongoose.Schema(
  {
    schoolCampus: {
      type:     mongoose.Schema.Types.ObjectId,
      ref:      'Campus',
      required: [true, 'Campus is required'],
      index:    true,
    },

    // Partner code captured from the cookie at quiz time
    partnerCode: {
      type:    String,
      trim:    true,
      uppercase: true,
      default: null,
    },

    // Anonymous token generated by the portal — kept even after linking to a lead.
    // The unique index is declared below via schema.index() — no index:true here
    // (otherwise Mongoose creates a duplicate index).
    sessionToken: {
      type:     String,
      required: [true, 'Session token is required'],
    },

    // Set after pre-registration — links the session to the prospect
    lead: {
      type:    mongoose.Schema.Types.ObjectId,
      ref:     'PartnerLead',
      default: null,
    },

    // Lifecycle: 'pending' once questions are served, 'completed' after scoring.
    // Default 'completed' keeps any legacy/direct creation backward-compatible.
    status: {
      type:    String,
      enum:    ['pending', 'completed'],
      default: 'completed',
    },

    // The exact question set served to this session — the authoritative
    // scoring denominator. The client cannot enlarge or shrink it at submit.
    servedQuestionIds: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref:  'QuizQuestion',
      },
    ],

    // TTL anchor: set on pending sessions (reaped if never submitted), cleared
    // to null on completion so finished sessions are retained for the leaderboard.
    expiresAt: {
      type:    Date,
      default: null,
    },

    // Display name for the leaderboard, e.g. 'Awa M. — Douala'.
    // Bounded length — this value is surfaced on the public leaderboard, so a
    // direct API caller must not be able to store an oversized/abusive label.
    displayName: {
      type:    String,
      trim:    true,
      maxlength: [60, 'displayName must not exceed 60 characters'],
      default: null,
    },

    city: {
      type:    String,
      trim:    true,
      maxlength: [80, 'city must not exceed 80 characters'],
      default: null,
    },

    country: {
      type:    String,
      trim:    true,
      maxlength: [80, 'country must not exceed 80 characters'],
      default: null,
    },

    category: {
      type:     String,
      required: [true, 'Category is required'],
      trim:     true,
      lowercase: true,
    },

    score: {
      type:    Number,
      min:     0,
      max:     100,
      default: 0,
    },

    correctAnswers: {
      type:    Number,
      min:     0,
      default: 0,
    },

    totalQuestions: {
      type:    Number,
      min:     0,
      default: 0,
    },

    completedAt: {
      type:    Date,
      default: null,
    },

    // SHA-256 only — never the raw IP
    ipAddressHash: {
      type:    String,
      default: null,
    },

    // Format 'YYYY-MM' — index for monthly leaderboard queries
    period: {
      type:    String,
      match:   [/^\d{4}-\d{2}$/, 'period must be in YYYY-MM format'],
      default: null,
      index:   true,
    },
  },
  {
    timestamps: true,
    toJSON:     { virtuals: true },
    toObject:   { virtuals: true },
  }
);

quizSessionSchema.index({ schoolCampus: 1, period: 1, score: -1 });
quizSessionSchema.index({ schoolCampus: 1, period: 1, category: 1, score: -1 });
quizSessionSchema.index({ sessionToken: 1 }, { unique: true });
// TTL: reap abandoned `pending` sessions. expireAfterSeconds:0 means "expire at
// the date stored in expiresAt"; docs with expiresAt:null are never collected.
quizSessionSchema.index({ expiresAt: 1 }, { expireAfterSeconds: 0 });

const QuizSession = mongoose.model('QuizSession', quizSessionSchema);
module.exports = QuizSession;
