'use strict';

/**
 * @file quiz.session.model.js
 * @description Quiz participation — anonymous session or linked to a lead.
 *
 * Before pre-registration : sessionToken identifies the participant anonymously.
 * After pre-registration  : lead (ObjectId) is set, sessionToken is kept.
 * period 'YYYY-MM'        : used to filter the monthly leaderboard.
 */

const mongoose = require('mongoose');

const quizSessionSchema = new mongoose.Schema(
  {
    schoolCampus: {
      type:     mongoose.Schema.Types.ObjectId,
      ref:      'Campus',
      required: [true, 'Campus is required'],
      index:    true,
    },

    // Partner code captured from the cookie at quiz time
    partnerCode: {
      type:    String,
      trim:    true,
      uppercase: true,
      default: null,
    },

    // Anonymous token generated by the portal — kept even after linking to a lead.
    // The unique index is declared below via schema.index() — no index:true here
    // (otherwise Mongoose creates a duplicate index).
    sessionToken: {
      type:     String,
      required: [true, 'Session token is required'],
    },

    // Set after pre-registration — links the session to the prospect
    lead: {
      type:    mongoose.Schema.Types.ObjectId,
      ref:     'PartnerLead',
      default: null,
    },

    // Display name for the leaderboard, e.g. 'Awa M. — Douala'
    displayName: {
      type:    String,
      trim:    true,
      default: null,
    },

    city: {
      type:    String,
      trim:    true,
      default: null,
    },

    country: {
      type:    String,
      trim:    true,
      default: null,
    },

    category: {
      type:     String,
      required: [true, 'Category is required'],
      trim:     true,
      lowercase: true,
    },

    score: {
      type:    Number,
      min:     0,
      max:     100,
      default: 0,
    },

    correctAnswers: {
      type:    Number,
      min:     0,
      default: 0,
    },

    totalQuestions: {
      type:    Number,
      min:     0,
      default: 0,
    },

    completedAt: {
      type:    Date,
      default: null,
    },

    // SHA-256 only — never the raw IP
    ipAddressHash: {
      type:    String,
      default: null,
    },

    // Format 'YYYY-MM' — index for monthly leaderboard queries
    period: {
      type:    String,
      match:   [/^\d{4}-\d{2}$/, 'period must be in YYYY-MM format'],
      default: null,
      index:   true,
    },
  },
  {
    timestamps: true,
    toJSON:     { virtuals: true },
    toObject:   { virtuals: true },
  }
);

quizSessionSchema.index({ schoolCampus: 1, period: 1, score: -1 });
quizSessionSchema.index({ schoolCampus: 1, period: 1, category: 1, score: -1 });
quizSessionSchema.index({ sessionToken: 1 }, { unique: true });

const QuizSession = mongoose.model('QuizSession', quizSessionSchema);
module.exports = QuizSession;
